- type: entity
  parent: BaseItem
  abstract: true
  id: FHWeaponBase
  components:
  - type: Wieldable
  - type: WieldableDoAfter
    timer: 0.5
  - type: GunWieldBonus
    minAngle: -47
    maxAngle: -47
    angleIncrease: 0
    angleDecay: 0
  - type: Gun
    minAngle: 50
    maxAngle: 50
    angleIncrease: 2.5
    angleDecay: 8
    soundEmpty:
      path: /Audio/_FinalHorizon/Weapons/Guns/Empty/gen_empty.ogg
  - type: SpeedModifiedOnWield
    walkModifier: 0.95
    sprintModifier: 0.95
  - type: PullDoAfter
    pullTime: 2
  - type: FarGunshot
    range: 150
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/ak_dist.ogg
  - type: EyeCursorOffset
    maxOffset: 16
    pvsIncrease: 1
  - type: HeldSpeedModifier
    walkModifier: 0.90
    sprintModifier: 0.90
  - type: CursorOffsetRequiresWield
  - type: EmitSoundOnPickup
    sound:
      path: /Audio/_FinalHorizon/Weapons/Guns/Draw/generic_draw.ogg
      params:
        volume: -2


- type: entity
  parent: FHWeaponBase
  abstract: true
  id: FHWeaponBaseLMG
  components:
  - type: WieldableDoAfter
    timer: 0.5
  - type: GunWieldBonus
    minAngle: -46
    maxAngle: -46
  - type: Gun
    angleIncrease: 1
  - type: PullDoAfter
    pullTime: 2
  - type: FarGunshot
    range: 150
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/mg_dist.ogg
  - type: EyeCursorOffset
    maxOffset: 16
    pvsIncrease: 1
  - type: HeldSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.85

- type: entity
  parent: FHWeaponBase
  abstract: true
  id: FHWeaponBaseSniper
  components:
  - type: WieldableDoAfter
    timer: 0.7
  - type: GunWieldBonus
    minAngle: -49
    maxAngle: -30
  - type: Gun
    angleIncrease: 5
    fireRate: 1.5
  - type: SpeedModifiedOnWield
    walkModifier: 0.80
    sprintModifier: 0.80
  - type: EyeCursorOffset
    maxOffset: 23
    pvsIncrease: 1.8

- type: entity
  parent: BaseItem
  id: FHWeaponLauncherBase
  components:
  - type: Wieldable
  - type: WieldableDoAfter
    timer: 0.5
  - type: HeldSpeedModifier
    walkModifier: 0.85
    sprintModifier: 0.85
  - type: PullDoAfter
    pullTime: 2
  - type: FarGunshot
    range: 150
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/rpg_dist.ogg
  - type: GunRequiresWield

- type: entity
  parent: BaseItem
  abstract: true
  id: FHWeaponBasePistol
  components:
  - type: Gun
    minAngle: 15
    maxAngle: 25
    angleIncrease: 2
    angleDecay: 10
    soundEmpty:
      path: /Audio/_FinalHorizon/Weapons/Guns/Empty/gen_empty.ogg
  - type: PullDoAfter
    pullTime: 0.3
  - type: FarGunshot
    range: 75
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/glock_dist.ogg
  - type: Clothing
    quickEquip: false
    slots:
    - Pocket
